### ISSUE TITLE
Error text

### ISSUE THREAD

**Issue by alexey267** [ntoneee/minecraft-telegram-bridge#9]
![Снимок экрана (38)](https://user-images.githubusercontent.com/59504323/201980757-f863fe18-d096-4dab-973c-8816ce0b0df4.png)

**Comment by ntoneee** [comment]
OS Windows? Windows could misinterpret the `lang.yml` file encoding, which is UTF-8, not cp1252.

**Comment by ntoneee** [comment]
Try to remove plugins/Minecraft-Telegram_Bridge/lang.yml and to launch [the latest version](https://github.com/ntoneee/minecraft-telegram-bridge/releases/tag/v2.0.2)
